# STEP : 1 - BUILD REACT APP

FROM node:alpine3.18
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

# STEP : 2 - SERVE WITH NGINX

FROM nginx:1.23-alpine
WORKDIR /user/share/nginx.html
RUN rm -rf *
COPY --from=build /app/build .
EXPOSE 80

ENTRYPOINT [ "nginc", "-g", "daemon off;" ]


