name: Production Deploy

on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
    
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t studyawsaeactapp .

      - name: Publish Image To Docker Hub
        run: docker push studyawsaeactapp:latest

