name: Production Deploy

on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:
    
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t mayankbharkhadaoptional/study-aws-react-app .

      - name: Publish Image To Docker Hub
        run: docker push mayankbharkhadaoptional/study-aws-react-app:latest

  deploy: 
    needs: build
    runs-on: self-hosted
    steps: 
      - name: Pull Image From Docker Hub
        run: docker pull mayankbharkhadaoptional/study-aws-react-app:latest
           - name: Delete Old Container
        run: |
          if [ $(docker ps -q -f name=studyAwsReactContainer) ]; then
            docker rm -f studyAwsReactContainer
          fi
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name studyAwsReactContainer mayankbharkhadaoptional/study-aws-react-app:latest
