name: Production Deploy

on: 
  push:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
    steps:

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        uses: docker/login-action@v1
        with: 
          username:  ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with: 
          context: .
          push: true
          tags: study-aws-react-app

      - name: Publish Image To Docker Hub
        run: docker push study-aws-react-app

